# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY Microsoft.SCIM.WebHostSample/*.csproj Microsoft.SCIM.WebHostSample/
RUN dotnet restore Microsoft.SCIM.WebHostSample/Microsoft.SCIM.WebHostSample.csproj

COPY . .

WORKDIR /src/Microsoft.SCIM.WebHostSample
RUN dotnet publish Microsoft.SCIM.WebHostSample.csproj -c Release -o /app/publish

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

ARG CONNECTION_STRING_HANGFIRE_DB
ARG CONNECTION_STRING_APPCONFIG

ENV ASPNETCORE_URLS=http://+:80
ENV ConnectionStrings:HangfireConnection=${CONNECTION_STRING_HANGFIRE_DB}
ENV ConnectionStrings:AppConfig=${CONNECTION_STRING_APPCONFIG}

EXPOSE 80

ENTRYPOINT ["dotnet", "Microsoft.SCIM.WebHostSample.dll"]