name: Project Build

on:
  push:
    branches: ["main", "dev","ci-cd-pipeline-modifications"]     
  pull_request:
    branches: ["main", "dev","ci-cd-pipeline-modifications"]

jobs:
  build-dotnet:
    name: .NET Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Microsoft.SCIM.WebHostSample/

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

 - name: Run Tests
        working-directory: ./KN.KloudIdentity.MapperTests/
        run: dotnet test KN.KloudIdentity.MapperTests.csproj --logger "console;verbosity=minimal"
        
    - name: Test
      run: dotnet test --no-restore --verbosity normal   